// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../OI.h"
#include "TestaMotor.h"

TestaMotor::TestaMotor() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);

}

// Called just before this Command runs the first time
void TestaMotor::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void TestaMotor::Execute() {
//	Robot::drivetrain->TestaMotor(.25);
}

// Make this return true when this Command no longer needs to run execute()
bool TestaMotor::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void TestaMotor::End() {
//	Robot::drivetrain->TestaMotor(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TestaMotor::Interrupted() {
	End();
}
