// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "../Commands/Driving.h"
#include "Drivetrain.h"
#include "../RobotMap.h"
#include <math.h>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Drivetrain::Drivetrain() : Subsystem("Drivetrain") {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	aMotor = RobotMap::drivetrainaMotor;
	bMotor = RobotMap::drivetrainbMotor;
	cMotor = RobotMap::drivetraincMotor;
	dMotor = RobotMap::drivetraindMotor;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

}
    
void Drivetrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.

	SetDefaultCommand(new Driving());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Drivetrain::ArcadeDrive(Joystick* joy) {
	 kw->ArcadeDrive(joy->GetY(), joy->GetX());
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

