// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "../Commands/UseSolenoid.h"
#include "Pneumatics.h"
#include "../RobotMap.h"
#include <math.h>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Pneumatics::Pneumatics() : Subsystem("Pneumatics") {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	testsolenoid = RobotMap::pneumaticstestsolenoid;
	test2solenoid = RobotMap::pneumaticstest2solenoid;


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// kw = new KiwiDrive(aMotor, bMotor, cMotor);
}

void Pneumatics::InitDefaultCommand() {
	// Set the default command for a subsystem here.

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Pneumatics::TestaSolenoid(Solenoid* sole){
	sole->Set(!sole->Get());
}

void Pneumatics::TestSolenoid(){
	 testsolenoid->Set(!testsolenoid->Get());
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

